package at.ac.csdc23vz_02.trading;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * Available stock quotes can be searched with the operation 'findStockQuotesByCompanyName'. The other operations generally accept a 'symbol' parameter that uniquely identifies a stock option.
 *
 * This class was generated by Apache CXF 3.5.1
 * 2022-12-22T10:34:56.859+01:00
 * Generated source version: 3.5.1
 *
 */
@WebService(targetNamespace = "http://trading.ws.dsfinance.froihofer.net/", name = "TradingWebService")
@XmlSeeAlso({ObjectFactory.class})
public interface TradingWebService {

    /**
     * Buys shares and returns the price per share effective for the buying transaction.
     */
    @WebMethod
    @RequestWrapper(localName = "buy", targetNamespace = "http://trading.ws.dsfinance.froihofer.net/", className = "at.ac.csdc23vz_02.trading.Buy")
    @ResponseWrapper(localName = "buyResponse", targetNamespace = "http://trading.ws.dsfinance.froihofer.net/", className = "at.ac.csdc23vz_02.trading.BuyResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.math.BigDecimal buy(

        @WebParam(name = "symbol", targetNamespace = "")
        java.lang.String symbol,
        @WebParam(name = "shares", targetNamespace = "")
        int shares
    ) throws TradingWSException_Exception;

    /**
     * Returns a list of the first 100 stock quotes where the company name contains the string specified in the 'partOfCompanyName' parameter
     */
    @WebMethod
    @RequestWrapper(localName = "findStockQuotesByCompanyName", targetNamespace = "http://trading.ws.dsfinance.froihofer.net/", className = "at.ac.csdc23vz_02.trading.FindStockQuotesByCompanyName")
    @ResponseWrapper(localName = "findStockQuotesByCompanyNameResponse", targetNamespace = "http://trading.ws.dsfinance.froihofer.net/", className = "at.ac.csdc23vz_02.trading.FindStockQuotesByCompanyNameResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<PublicStockQuote> findStockQuotesByCompanyName(

        @WebParam(name = "partOfCompanyName", targetNamespace = "")
        java.lang.String partOfCompanyName
    ) throws TradingWSException_Exception;

    /**
     * Sells shares and returns the price per share effective for the selling transaction.
     */
    @WebMethod
    @RequestWrapper(localName = "sell", targetNamespace = "http://trading.ws.dsfinance.froihofer.net/", className = "at.ac.csdc23vz_02.trading.Sell")
    @ResponseWrapper(localName = "sellResponse", targetNamespace = "http://trading.ws.dsfinance.froihofer.net/", className = "at.ac.csdc23vz_02.trading.SellResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.math.BigDecimal sell(

        @WebParam(name = "symbol", targetNamespace = "")
        java.lang.String symbol,
        @WebParam(name = "shares", targetNamespace = "")
        int shares
    ) throws TradingWSException_Exception;

    /**
     * Returns the stock quotes for the stock options identified by the 'symbols' parameter.
     */
    @WebMethod
    @RequestWrapper(localName = "getStockQuotes", targetNamespace = "http://trading.ws.dsfinance.froihofer.net/", className = "at.ac.csdc23vz_02.trading.GetStockQuotes")
    @ResponseWrapper(localName = "getStockQuotesResponse", targetNamespace = "http://trading.ws.dsfinance.froihofer.net/", className = "at.ac.csdc23vz_02.trading.GetStockQuotesResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<PublicStockQuote> getStockQuotes(

        @WebParam(name = "symbols", targetNamespace = "")
        java.util.List<java.lang.String> symbols
    ) throws TradingWSException_Exception;

    /**
     * Returns a list of historical stock quotes, limited to a few months in the past.
     */
    @WebMethod
    @RequestWrapper(localName = "getStockQuoteHistory", targetNamespace = "http://trading.ws.dsfinance.froihofer.net/", className = "at.ac.csdc23vz_02.trading.GetStockQuoteHistory")
    @ResponseWrapper(localName = "getStockQuoteHistoryResponse", targetNamespace = "http://trading.ws.dsfinance.froihofer.net/", className = "at.ac.csdc23vz_02.trading.GetStockQuoteHistoryResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<PublicStockQuote> getStockQuoteHistory(

        @WebParam(name = "symbol", targetNamespace = "")
        java.lang.String symbol
    ) throws TradingWSException_Exception;
}
